# Generated by Django 5.1.6 on 2025-02-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='GoogleUser',
        ),
    ]
